# Import Libraries
---

In [69]:
import pandas as pd
import numpy as np

**Load the dataset**

---

In [70]:
# Read the .csv file
df = pd.read_csv('data/AmesHousing.csv')



---

In [71]:
# Display the first 5 rows of the data
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [72]:
# Shape of the data (Rows, Columns)
df.shape

(2930, 82)

In [73]:
# Check for duplicated rows
df.duplicated().sum()

np.int64(0)

In [74]:
# Looking at the columns that missing values exceed 25% of their rows
missing_pct = (df.isna().sum() / len(df) * 100)
missing_pct[missing_pct > 25].sort_values(ascending=False)

Pool QC         99.556314
Misc Feature    96.382253
Alley           93.242321
Fence           80.477816
Mas Vnr Type    60.580205
Fireplace Qu    48.532423
dtype: float64

In [75]:
# Drop the columns (included the Order, PID columns)
df.drop(columns=['Order', 'PID', 'Pool QC', 'Misc Feature', 'Alley', 'Fence', 'Mas Vnr Type', 'Fireplace Qu'], inplace=True)

In [76]:
# Looking at the data and column types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 74 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   MS SubClass      2930 non-null   int64
 1   MS Zoning        2930 non-null   object
 2   Lot Frontage     2440 non-null   float64
 3   Lot Area         2930 non-null   int64
 4   Street           2930 non-null   object
 5   Lot Shape        2930 non-null   object
 6   Land Contour     2930 non-null   object
 7   Utilities        2930 non-null   object
 8   Lot Config       2930 non-null   object
 9   Land Slope       2930 non-null   object
 10  Neighborhood     2930 non-null   object
 11  Condition 1      2930 non-null   object
 12  Condition 2      2930 non-null   object
 13  Bldg Type        2930 non-null   object
 14  House Style      2930 non-null   object
 15  Overall Qual     2930 non-null   int64
 16  Overall Cond     2930 non-null   int64
 17  Year Built       2930 non-null   int64
 18  Year Remod/Add   2930 non-null   int64
 19  Roof Style       2930 non-null   object
 20  Roof Matl        2930 non-null   object
 21  Exterior 1st     2930 non-null   object
 22  Exterior 2nd     2930 non-null   object
 23  Mas Vnr Area     2907 non-null   float64
 24  Exter Qual       2930 non-null   object
 25  Exter Cond       2930 non-null   object
 26  Foundation       2930 non-null   object
 27  Bsmt Qual        2850 non-null   object
 28  Bsmt Cond        2850 non-null   object
 29  Bsmt Exposure    2847 non-null   object
 30  BsmtFin Type 1   2850 non-null   object
 31  BsmtFin SF 1     2929 non-null   float64
 32  BsmtFin Type 2   2849 non-null   object
 33  BsmtFin SF 2     2929 non-null   float64
 34  Bsmt Unf SF      2929 non-null   float64
 35  Total Bsmt SF    2929 non-null   float64
 36  Heating          2930 non-null   object
 37  Heating QC       2930 non-null   object
 38  Central Air      2930 non-null   object
 39  Electrical       2929 non-null   object
 40  1st Flr SF       2930 non-null   int64
 41  2nd Flr SF       2930 non-null   int64
 42  Low Qual Fin SF  2930 non-null   int64
 43  Gr Liv Area      2930 non-null   int64
 44  Bsmt Full Bath   2928 non-null   float64
 45  Bsmt Half Bath   2928 non-null   float64
 46  Full Bath        2930 non-null   int64
 47  Half Bath        2930 non-null   int64
 48  Bedroom AbvGr    2930 non-null   int64
 49  Kitchen AbvGr    2930 non-null   int64
 50  Kitchen Qual     2930 non-null   object
 51  TotRms AbvGrd    2930 non-null   int64
 52  Functional       2930 non-null   object
 53  Fireplaces       2930 non-null   int64
 54  Garage Type      2773 non-null   object
 55  Garage Yr Blt    2771 non-null   float64
 56  Garage Finish    2771 non-null   object
 57  Garage Cars      2929 non-null   float64
 58  Garage Area      2929 non-null   float64
 59  Garage Qual      2771 non-null   object
 60  Garage Cond      2771 non-null   object
 61  Paved Drive      2930 non-null   object
 62  Wood Deck SF     2930 non-null   int64
 63  Open Porch SF    2930 non-null   int64
 64  Enclosed Porch   2930 non-null   int64
 65  3Ssn Porch       2930 non-null   int64
 66  Screen Porch     2930 non-null   int64
 67  Pool Area        2930 non-null   int64
 68  Misc Val         2930 non-null   int64
 69  Mo Sold          2930 non-null   int64
 70  Yr Sold          2930 non-null   int64
 71  Sale Type        2930 non-null   object
 72  Sale Condition   2930 non-null   object
 73  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(26), object(37)
memory usage: 1.7+ MB

In [77]:
# Check for no of unique values for each column
df.nunique().sort_values(ascending=False)

Lot Area         1960
Gr Liv Area      1292
Bsmt Unf SF      1137
1st Flr SF       1083
Total Bsmt SF    1058
                 ...
Garage Finish       3
Paved Drive         3
Half Bath           3
Street              2
Central Air         2
Length: 74, dtype: int64

In [78]:
# Looking at the data for possible outliers
df.describe()

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2930.000000,2440.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2907.000000,2929.000000,2929.000000,...,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000
mean,57.387372,69.224590,10147.921843,6.094881,5.563140,1971.356314,1984.266553,101.896801,442.629566,49.722431,...,93.751877,47.533447,23.011604,2.592491,16.002048,2.243345,50.635154,6.216041,2007.790444,180796.060068
std,42.638025,23.365335,7880.017759,1.411026,1.111537,30.245361,20.860286,179.112611,455.590839,169.168476,...,126.361562,67.483400,64.139059,25.141331,56.087370,35.597181,566.344288,2.714492,1.316613,79886.692357
min,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,20.000000,58.000000,7440.250000,5.000000,5.000000,1954.000000,1965.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,50.000000,68.000000,9436.500000,6.000000,5.000000,1973.000000,1993.000000,0.000000,370.000000,0.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,70.000000,80.000000,11555.250000,7.000000,6.000000,2001.000000,2004.000000,164.000000,734.000000,0.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000
max,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1526.000000,...,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

# Remove the outliers & Fill missing values

---

In [79]:
# All numeric columns except ['Year Built', 'Year Remod/Add', 'Garage Yr Blt'], using IQR Method
for column in df.select_dtypes(include=['int64', 'float64']):

  # Skip the 'Year' columns
  if column in ['Year Built', 'Year Remod/Add', 'Garage Yr Blt']:
    continue

  # 4. Impute missing values using the clean dataset's mean
  df[column] = df[column].fillna(df[column].mean())

In [80]:
# Check the data after cleaning
df.describe()

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,...,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000
mean,57.387372,69.224590,10147.921843,6.094881,5.563140,1971.356314,1984.266553,101.896801,442.629566,49.722431,...,93.751877,47.533447,23.011604,2.592491,16.002048,2.243345,50.635154,6.216041,2007.790444,180796.060068
std,42.638025,21.321523,7880.017759,1.411026,1.111537,30.245361,20.860286,178.407983,455.513060,169.139595,...,126.361562,67.483400,64.139059,25.141331,56.087370,35.597181,566.344288,2.714492,1.316613,79886.692357
min,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,20.000000,60.000000,7440.250000,5.000000,5.000000,1954.000000,1965.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,50.000000,69.224590,9436.500000,6.000000,5.000000,1973.000000,1993.000000,0.000000,370.500000,0.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,70.000000,78.000000,11555.250000,7.000000,6.000000,2001.000000,2004.000000,162.750000,734.000000,0.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000
max,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1526.000000,...,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

In [81]:
# Get the categorical columns
categorical_features = [col for col in df.columns if df[col].dtype == 'O']

In [82]:
# Impute missing values using the mode method
for col in categorical_features:
  df[col].fillna(df[col].mode()[0], inplace=True)

for col in ['Year Built', 'Year Remod/Add', 'Garage Yr Blt']:
  df[col].fillna(df[col].mode()[0], inplace=True)

In [83]:
# Look at the shape after removing the outliers (Rows, Columns)
df.shape

(2930, 74)

# Save the cleaned data

---

In [84]:
# Save the cleaned data
df.to_csv('data/Ames_Cleaned_data.csv')